include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: build context
    type: script
    file: "$SERVICE_PATH/instance/build_context"
    configuration:
      K8S_NAMESPACE: $K8S_NAMESPACE
  - name: logs
    type: script
    file: "$SERVICE_PATH/instance/list"
