steps:
  - name: build context
    type: script
    file: "$SERVICE_PATH/metric/build_context"
    configuration:
      K8S_NAMESPACE: nullplatform
  - name: metric
    type: script
    file: "$SERVICE_PATH/metric/metric"