steps:
  - name: validate_port
    description: Validates the application exposes an http server in the 8080 port.
    category: application
    type: script
    file: "$SERVICE_PATH/diagnose/application/pod_status_overview"