steps:
  - name: dns_configuration
    description: Validates dns config.
    category: networking
    type: script
    file: "$SERVICE_PATH/diagnose/networking/dns_configuration"
  - name: port_info
    description: Validates the application exposes an http server in the 8080 port.
    category: networking
    type: script
    file: "$SERVICE_PATH/diagnose/networking/port_info"